development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://dhjutpkizijedg:c8b3568e2d80e17902f45072c2a62afa023464efe59d2184c87dd00f792dd7a4@ec2-54-235-169-191.compute-1.amazonaws.com:5432/d7b6r7r9f8ofh8

# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: nameofapp_production
